import { Footer } from '@/Components/Footer/Footer'
import { Header } from '@/Components/Header/Header'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
