import { Footer } from '@/Components/Footer/Footer'
import Providers from '../redux/ReduxProvider'
import type { Metadata } from 'next'
import Header2 from '@/Components/Header2/Header2'
import Loader from '@/Components/Loader/Loader'
import { MainStyled } from './HomePage.styled'


export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}
function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>
          <Header2 />
          <MainStyled>
            {children}
          </MainStyled>
          <Footer />
          <Loader/>
        </Providers>
      </body>
    </html>
  )
}
export default RootLayout;