import { Footer } from '@/Components/Footer/Footer'
import Providers from '../redux/ReduxProvider'
import type { Metadata } from 'next'
import Header2 from '@/Components/Header2/Header2'
import Loader from '@/Components/Loader/Loader'


export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>
          <Header2 />
          {children}
          <Footer />
          <Loader/>
        </Providers>
        </body>
     
    </html>
  )
}
